# Generated by Django 5.1.5 on 2025-02-02 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_started', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Current', models.JSONField(default=dict)),
                ('Answer_type', models.JSONField(default=dict)),
                ('Time_taken', models.JSONField(default=dict)),
                ('Answer', models.JSONField(default=dict)),
                ('Test', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='API.test')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TestStatus',
        ),
    ]
