# Generated by Django 5.1.5 on 2025-02-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_currenttest_delete_teststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenttest',
            name='Answer_type',
            field=models.JSONField(default=dict, help_text='U = Unseen(Grey), S = Seen but not answered(Red), A = Answered(Green), M = Marked for Review(Purple), AM = Answered but Marked for Review(Purple with green)'),
        ),
    ]
