# Generated by Django 5.1.5 on 2025-02-03 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_currenttest_answer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='Negative',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='Positive',
        ),
        migrations.AlterField(
            model_name='questions',
            name='Number',
            field=models.IntegerField(editable=False, verbose_name='Number of Questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Type',
            field=models.CharField(choices=[('SCQ', 'Single Choice Question'), ('MCQ', 'Multiple Choice Question'), ('Paragraph 1', 'Paragraph 1 Questions'), ('Paragraph 2', 'Paragraph 2 Questions'), ('Paragraph 4', 'Paragraph 3 Questions'), ('Matching', 'Matching Type Questions'), ('Integer', 'Integer based Question'), ('Single Digit', 'Single Digit Integer based Question')], editable=False, max_length=12),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(editable=False, verbose_name='Number of Questions')),
                ('Positive', models.IntegerField(default=4, help_text='Marks for Correct Answer', verbose_name='Marks')),
                ('Negative', models.IntegerField(default=0, help_text='Marks for Wrong Answer', verbose_name='Negative Marks')),
                ('Type', models.CharField(choices=[('SCQ', 'Single Choice Question'), ('MCQ', 'Multiple Choice Question'), ('Paragraph 1', 'Paragraph 1 Questions'), ('Paragraph 2', 'Paragraph 2 Questions'), ('Paragraph 4', 'Paragraph 3 Questions'), ('Matching', 'Matching Type Questions'), ('Integer', 'Integer based Question'), ('Single Digit', 'Single Digit Integer based Question')], editable=False, max_length=12)),
                ('Test', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='API.test')),
            ],
        ),
    ]
