# Generated by Django 5.1.5 on 2025-02-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
